export enum EventCategory {  
  
 
    COMMERCIAL= 'COMMERCIAL',
    AGGREGATION= 'AGGREGATION',
    EDUCATIONAL= 'EDUCATIONAL',
    CULTURAL= 'CULTURAL',
    SOCIAL= 'SOCIAL',
    SCIENTIFIC= 'SCIENTIFIC',
    TECHNOLOGICAL= 'TECHNOLOGICAL',
    TELEVISION= 'TELEVISION',
    RADIO= 'RADIO',
    GEOLOGICAL= 'GEOLOGICAL',
    BOTANICAL= 'BOTANICAL',
    ZOOLOGICAL= 'ZOOLOGICAL',
    ETHNOGRAPHIC= 'ETHNOGRAPHIC',
    FOOD= 'FOOD',
    AGRICULTURAL= 'AGRICULTURAL',
    INDUSTRIAL= 'INDUSTRIAL',
    
}